# ------------
# | Wrappers |
# ------------
[tasks.fmt]
command = "cargo"
args = ["fmt"]
private = true

[tasks.check]
command = "cargo"
args = ["check"]
private = true

[tasks.clippy]
command = "cargo"
args = ["clippy"]
private = true

# -------------
# | Executors |
# -------------
[tasks.checkf]
dependencies = ["fmt", "check"]

[tasks.checkfc]
dependencies = ["fmt", "check", "clippy"]

[tasks.run]
dependencies = ["checkf"]
command = "cargo"
args = ["run"]

[tasks.runw]
dependencies = ["checkf"]
command = "cargo"
args = ["run"]
watch = true

[tasks.docker-build]
workspace = false
command = "nix-build"
args = ["docker.nix"]

[tasks.docker-load]
workspace = false
script_runner = "@shell"
script = '''
docker load < result
'''

[tasks.docker-run]
deprecated = true
command = "docker"
args = [
  "run",
  "--name", "DosBot",
  "-v", "/var/lib/dos-bot:/.dos-bot",
  "fuwn/dos-bot"
]

[tasks.docker-run-i]
deprecated = true
command = "docker"
args = [
  "run",
  "-it",
  "--name", "DosBot",
  "-v", "/var/lib/dos-bot:/.dos-bot",
  "fuwn/dos-bot"
]

# Build 'n' load
[tasks.bnl]
dependencies = ["docker-build", "docker-load"]

[tasks.gen-docs]
toolchain = "nightly"
command = "cargo"
args = ["doc", "--open", "--document-private-items", "--no-deps"]
